import React, { useState, useEffect, useRef } from 'react';
import { MessageSquare, Send, X, Sparkles, AlertCircle, ShoppingCart, Tag, MapPin } from 'lucide-react';
import { ChatMessage, Product, UserPersona } from '../types';

interface AIChatAssistantProps {
  userPersona: UserPersona;
  onNavigateToCategory: (category: string) => void;
  onSelectProduct: (product: Product) => void;
  onStartCheckout: (product: Product) => void;
}

export default function AIChatAssistant({ userPersona, onNavigateToCategory, onSelectProduct, onStartCheckout }: AIChatAssistantProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'welcome',
      role: 'assistant',
      content: `Hello! I am your Social Shopperfy Smart AI Assistant. Tell me what you are looking for today, or type "show categories" to discover our curated inventory. Don't forget, you can use the referral code "MUSA2024" at checkout for an instant 10% discount!`,
      timestamp: new Date().toISOString()
    }
  ]);
  const [loading, setLoading] = useState(false);
  const [aiProductResults, setAiProductResults] = useState<Product[]>([]);

  const chatEndRef = useRef<HTMLDivElement>(null);

  // Auto scroll to bottom on new message
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, loading]);

  const handleSend = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || loading) return;

    const userMsg: ChatMessage = {
      id: `user-${Date.now()}`,
      role: 'user',
      content: input,
      timestamp: new Date().toISOString()
    };

    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setLoading(true);
    setAiProductResults([]);

    try {
      const response = await fetch('/api/ai/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: messages.concat(userMsg).map(m => ({ role: m.role, content: m.content })),
          userPersona
        })
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || 'Server returned an error');
      }

      const assistantMsg: ChatMessage = {
        id: `ai-${Date.now()}`,
        role: 'assistant',
        content: data.content,
        timestamp: new Date().toISOString()
      };

      setMessages(prev => [...prev, assistantMsg]);

      // Check for custom UI actions generated by function calling
      if (data.uiAction) {
        if (data.uiAction.type === 'search_results' && data.uiAction.products) {
          setAiProductResults(data.uiAction.products);
        } else if (data.uiAction.type === 'navigate' && data.uiAction.category) {
          onNavigateToCategory(data.uiAction.category);
          setMessages(prev => [
            ...prev,
            {
              id: `sys-${Date.now()}`,
              role: 'assistant',
              content: `Navigated to the ${data.uiAction.category} catalog view for you.`,
              timestamp: new Date().toISOString()
            }
          ]);
        }
      }

    } catch (err: any) {
      console.error('[AI Assist Error]:', err);
      setMessages(prev => [
        ...prev,
        {
          id: `err-${Date.now()}`,
          role: 'assistant',
          content: `I am experiencing connectivity issues right now: ${err.message || 'Unknown network error'}. Please try again shortly.`,
          timestamp: new Date().toISOString()
        }
      ]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed bottom-6 right-6 z-50 font-sans" id="ai-chat-drawer-container">
      {/* Mini Toggle Floating Button */}
      {!isOpen && (
        <button
          onClick={() => setIsOpen(true)}
          className="w-14 h-14 rounded-full bg-gradient-to-r from-primary to-secondary text-black shadow-neon-green flex items-center justify-center hover:scale-110 active:scale-95 transition-all cursor-pointer group"
          id="toggle-ai-chat-btn"
        >
          <MessageSquare className="w-6 h-6 group-hover:rotate-12 transition-transform" />
          {/* Unread dot */}
          <span className="absolute top-1 right-1 w-3 h-3 bg-red-500 rounded-full border border-black animate-ping"></span>
        </button>
      )}

      {/* Main Drawer Interface */}
      {isOpen && (
        <div
          className="w-[360px] md:w-[400px] h-[550px] rounded-2xl glass-card border border-primary/20 flex flex-col overflow-hidden shadow-2xl transition-all duration-300"
          id="ai-chat-drawer"
        >
          {/* Header */}
          <div className="px-5 py-4 bg-dark-surface border-b border-white/5 flex items-center justify-between">
            <div className="flex items-center gap-2.5">
              <div className="w-2.5 h-2.5 rounded-full bg-primary animate-pulse"></div>
              <div>
                <h3 className="text-sm font-display font-bold text-white flex items-center gap-1">
                  MUSA AI ASSISTANT
                  <Sparkles className="w-3.5 h-3.5 text-primary" />
                </h3>
                <p className="text-[10px] text-gray-500 font-mono uppercase tracking-wider">
                  Persona Mode: {userPersona || 'Value'}
                </p>
              </div>
            </div>
            <button
              onClick={() => setIsOpen(false)}
              className="p-1 rounded-full text-gray-400 hover:text-white hover:bg-white/5 transition-colors cursor-pointer"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          {/* Scrollable messages area */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4 scrollbar-thin bg-neutral-950/40">
            {messages.map(msg => (
              <div
                key={msg.id}
                className={`flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'}`}
              >
                <div
                  className={`max-w-[85%] rounded-2xl px-4 py-2.5 text-xs leading-relaxed ${
                    msg.role === 'user'
                      ? 'bg-secondary text-white rounded-tr-none'
                      : 'bg-dark-surface border border-white/5 text-gray-200 rounded-tl-none'
                  }`}
                >
                  {msg.content}
                </div>
                <span className="text-[9px] text-gray-600 font-mono mt-1 px-1">
                  {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </span>
              </div>
            ))}

            {/* AI Custom Tool Card Results Grid (within chat window) */}
            {aiProductResults.length > 0 && (
              <div className="p-2 rounded-xl border border-primary/10 bg-primary/5 space-y-3 mt-2">
                <div className="text-[10px] font-mono text-primary font-bold">MATCHES LOGGED FROM LEDGER:</div>
                <div className="space-y-2">
                  {aiProductResults.map(p => (
                    <div
                      key={p.id}
                      onClick={() => { onSelectProduct(p); setIsOpen(false); }}
                      className="flex gap-2.5 p-2 rounded-lg bg-neutral-900 border border-white/5 hover:border-primary/20 cursor-pointer transition-all"
                    >
                      <img src={p.images[0]} alt={p.name} className="w-12 h-12 rounded object-cover" referrerPolicy="no-referrer" />
                      <div className="flex-1 min-w-0">
                        <h4 className="text-xs font-bold text-white truncate">{p.name}</h4>
                        <div className="flex items-center justify-between mt-1">
                          <span className="text-[11px] font-mono text-primary font-bold">₦{p.price_ngn.toLocaleString()}</span>
                          <button
                            onClick={(e) => { e.stopPropagation(); onStartCheckout(p); setIsOpen(false); }}
                            className="p-1 rounded bg-primary text-black hover:bg-white transition-colors"
                            title="Instant Checkout"
                          >
                            <ShoppingCart className="w-3.5 h-3.5" />
                          </button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Loader */}
            {loading && (
              <div className="flex items-center gap-2 text-xs text-primary font-mono bg-primary/5 border border-primary/10 px-3 py-1.5 rounded-lg w-fit animate-pulse">
                <Sparkles className="w-3.5 h-3.5 animate-spin" />
                Musa is searching database...
              </div>
            )}
            <div ref={chatEndRef}></div>
          </div>

          {/* Quick recommendation chips */}
          <div className="px-3 py-2 bg-neutral-950/60 flex gap-2 overflow-x-auto scrollbar-none border-t border-white/5">
            {[
              'Show noise-cancelling headphones',
              'Do you have suede loafers?',
              'Explain shipping fees',
              'Give me a discount'
            ].map(chip => (
              <button
                key={chip}
                onClick={() => setInput(chip)}
                className="px-2.5 py-1 rounded bg-neutral-900 border border-white/5 hover:border-primary/30 text-[10px] text-gray-400 hover:text-white whitespace-nowrap cursor-pointer transition-colors"
              >
                {chip}
              </button>
            ))}
          </div>

          {/* Chat input form */}
          <form onSubmit={handleSend} className="p-4 bg-dark-surface border-t border-white/5 flex gap-2">
            <input
              type="text"
              placeholder="Ask Musa Assistant..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
              className="flex-1 px-4 py-2 text-xs bg-neutral-950 border border-white/10 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:border-primary"
              id="ai-chat-input-field"
            />
            <button
              type="submit"
              disabled={!input.trim() || loading}
              className="px-4 py-2 bg-primary text-black rounded-lg hover:shadow-neon-green transition-all flex items-center justify-center disabled:opacity-40 disabled:hover:shadow-none cursor-pointer"
              id="send-ai-chat-btn"
            >
              <Send className="w-3.5 h-3.5" />
            </button>
          </form>
        </div>
      )}
    </div>
  );
}
